### ISSUE TITLE
Add a way to get the rosparams to populate the root service

### ISSUE THREAD

**Issue by Hugal31** [orocos/rtt_ros_integration#167]
For now, there is no way to populate the "root service" of a TaskContext with a custom ros param name. But it is possible with a sub service:

```
rosparam set /bar/int 42
rosparam set /bar/string "forty-two"
```

```
loadComponent("foo", "Components::Foo")
loadService("foo", "rosparam")
// Will populate foo.bar properties
foo.rosparam.getParam("/bar", "bar")
// Will fail with [ Debug  ][ROSParamService::getParam] RTT component does not have a property or service named ""
foo.rosparam.getParam("/bar", "")
```

There is no way to populate "foo" with properties from "/bar". This could be easily achieved by adding for example a check for `""` [here](https://github.com/orocos/rtt_ros_integration/blob/df79afb7a7b6e90ea7b807f0e4322662caee8c07/rtt_rosparam/src/rtt_rosparam_service.cpp#L924).

**Comment by meyerj** [comment]
What exactly would you expect as a result? What properties of what types actually exist in `Components::Foo`? Does it already have a service or property called `"bar"`?

If it has two individual properties `int` and `string`, how about
```cpp
// getParams() is meant to load multiple properties from an XmlRpcStruct,
// i.e. a non-leaf node of the ROS parameter tree.
foo.rosparam.getParams("/bar")
```
? If the names of ROS parameters and corresponding RTT properties do not match, you would have to load them separately with
```cpp
foo.rosparam.getParam("/bar/int", "property_that_int_should_be_loaded_to")
foo.rosparam.getParam("/bar/string", "property_that_string_should_be_loaded_to")
```

At the moment the `rosparam` service never creates new properties, because there is no unambiguous way to determine the C++ type from the XmlRpc type. Is that what you want to achieve? If yes, how would you map from XmlRpc types to C++ types?

**Comment by Hugal31** [comment]
The properties already exist in the "root" service.

`foo.rosparam.getParams("/bar")` would be nice.

**Comment by meyerj** [comment]
Ah, it exists as a [C++ method](https://github.com/orocos/rtt_ros_integration/blob/df79afb7a7b6e90ea7b807f0e4322662caee8c07/rtt_rosparam/src/rtt_rosparam_service.cpp#L946), but is not registered as an operation in the `rosparam` service yet.

Would you open a pull request, please, that adds a wrapper function
```
bool ROSParamService::getParams(const std::string& ns) {
  return getParams(this->getOwner()->provides(), ns);
}
```
and registers that in the `ROSParamService` constructor? I did not test it, but that should do the job.
