### ISSUE TITLE
rtt_tf does not compile on indigo

### ISSUE THREAD

**Issue by smits** [orocos/rtt_ros_integration#24]
I get the following compile error: 

```
home/rsmits/orocos_ws/src/rtt_ros_integration/rtt_tf/rtt_tf-component.cpp: In member function ‘virtual void rtt_tf::RTT_TF::updateHook()’:
/home/rsmits/orocos_ws/src/rtt_ros_integration/rtt_tf/rtt_tf-component.cpp:133:22: error: ‘tf::tfMessage’ has no member named ‘__connection_header’
               msg_in.__connection_header.get();
```

It's related to the following discussion in https://github.com/ros/gencpp/issues/3.

**Comment by jbohren** [comment]
Yeah, I actually want to add a bunch to `rtt_tf`, including making it usable internally to an orocos process without spamming the `/tf` topic at hundreds of hz (#15). After we decide on #21, I think we should be close to finalizing for Hydro.

After that, we should probably finish up merging `rtt_rosclock` and the ROS simulation time stuff in [`rtt_gazebo_activity`](https://github.com/jhu-lcsr/rtt_gazebo/tree/master/rtt_gazebo_activity) into `rtt_ros_time` and tackle the updates to `rtt_tf` for Indigo.

**Comment by meyerj** [comment]
Sounds good! Additionally I am close to finish [rtt_dynamic_reconfigure](https://github.com/meyerj/rtt_ros_integration/tree/rtt_dynamic_reconfigure) which also could be included for the hydro release.

One possibility to circumvent the problem of the removed `__connection_header` member in messages would be to instantiate the publisher and subscriber directly and implement a `ros::MessageEvent<tfMessage>` callback instead of using ROS stream connections. This would also remove the dependency on rtt_roscomm. I do not see any drawbacks as the underlying `tf::Transformer` is probably not real-time safe anyway.

Let's keep that for indigo once we finally have released rtt_ros_integration in hydro.

**Comment by meyerj** [comment]
Pull request in https://github.com/orocos/rtt_ros_integration/pull/31.

**Comment by meyerj** [comment]
Merged https://github.com/orocos/rtt_ros_integration/pull/31.
