### ISSUE TITLE
rtt_rosnode modifies the deployer's argv

### ISSUE THREAD

**Issue by ahoarau** [orocos/rtt_ros_integration#54]
Script to test (rtt 2.8 - 14.04) : 

``` python
require("print")
require("os")

// Get Arguments

var strings argv = os.argv()

print.ln("Arguments :")
for(var int i = 0 ; i < argv.size ; i = i + 1){
    print.ln(argv[i])
}

print.ln("Number of args :"+os.argc())

// Importing ROS
import("rtt_ros")
import("rtt_rospack")
ros.import("rtt_rosnode")


// Double check ?

argv = os.argv()
print.ln("-----------------------")
print.ln("Arguments after rosnode :")
for(i = 0 ; i < argv.size ; i = i + 1){
    print.ln(argv[i])
}

print.ln("Number of args :"+os.argc())
```

``` bash
 deployer -s rosnode_bug.ops  -- _arg1:=a _arg2:=b _arg3:=c _arg4:=d
```

Output : 

```
Arguments :
 /home/hoarau/orocos_ws/install/bin/deployer-gnulinux
 _arg1:=a
 _arg2:=b
 _arg3:=c
 _arg4:=d
Number of args :5
-----------------------
Arguments after rosnode :
 /home/hoarau/orocos_ws/install/bin/deployer-gnulinux
 _arg4:=d
 _arg1:=a
 _arg1:=a
 _arg1:=a
Number of args :5

```

I think it should pass a copy of `__os_main_argv()`  instead of the `char **`
https://github.com/orocos/rtt_ros_integration/blob/indigo-devel/rtt_rosnode/src/ros_plugin.cpp#L47

> note: the ros params are correctly set

**Comment by meyerj** [comment]
True, this looks like a bug. But there are two possible solutions:
- copy the arguments to a `std::vector<const char *> argvv` and pass `argvv.data()` to `ros::init()` as suggested
- let `__os_main_argc(void)` return an int reference so that `ros::init()` can also update the counter variable (to 1 in your example)

`ros::init(argc, argv, ...)` is designed to modify ("consume") the remapping arguments, so that another command line parser later on would not complain about unknown options [1]. In case of rtt_rosnode this happens too late to hide the remapping arguments from the deployer, but for other plugins it might still be useful if they are loaded after rtt_rosnode. That is also the reason why you have to add a double-dash in the deployer command line before any remapping arguments [2].

As I am not aware of any other plugin that parses command line arguments and no plugin should depend on the exact order in which it is loaded anyway, I would vote for the first option.

[1] http://wiki.ros.org/roscpp/Overview/Initialization%20and%20Shutdown#Initializing_the_roscpp_Node
[2] http://wiki.ros.org/ocl#Roslaunch_for_OROCOS_components
